[env]
platform = espressif32
framework = arduino

lib_deps = 
    xreef/EByte LoRa E32 library@^1.5.13
    olikraus/U8g2@^2.36.18
    bxparks/AceCRC@^1.1.1

build_flags =
    -DDEBUG_ENABLED
    -DUSE_DISPLAY


[env:esp32doit-devkit-v1]
extends = env
board = esp32doit-devkit-v1

lib_deps =
    ${env.lib_deps}

build_flags =
    ${env.build_flags}
    -DBOARD_ESP32DOIT

build_type = debug

board_build.partitions = partitions.csv
extra_scripts = 
    pre:extra_script.py
    post:upload_nvs.py

upload_speed = 115200
upload_port = COM13

monitor_speed = 115200
monitor_port = COM10
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder

[env:esp32c3_mini]
extends = env
board = esp32-c3-devkitm-1

lib_deps =
    ${env.lib_deps}
    plerup/EspSoftwareSerial@^8.2.0

build_flags =
    ${env.build_flags}
    -DBOARD_ESP32C3
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    ;-DCORE_DEBUG_LEVEL=4

build_type = debug

board_build.flash_mode = dio
board_build.partitions = partitions.csv
extra_scripts = 
    pre:extra_script.py
    post:upload_nvs.py

upload_speed = 921600
upload_port = COM14

monitor_speed = 19200 ; software serial is slow
monitor_port = COM10
monitor_rts = 0
monitor_dtr = 0
monitor_filters = esp32_exception_decoder